### ISSUE TITLE
Error while trying to call snps " UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 948: ordinal not in range(128)"

### ISSUE THREAD

**Issue by herrroaa** [mroosmalen/nanosv#47] opened 2018-07-20 22:37 UTC
Hi,
I am trying to call snps from bam fil generated by minimap2, but I got an error

`NanoSV BC01_sorted.bam -o BC01.vcf`

I got this error message
` UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 948: ordinal not in range(128)`

Here is the complete output
```
Traceback (most recent call last):
  File "/Users/tarekmagdyshehatamohamed/miniconda3/envs/bioinfo/bin/NanoSV", line 7, in <module>
    from nanosv.NanoSV import main
  File "/Users/tarekmagdyshehatamohamed/miniconda3/envs/bioinfo/lib/python3.6/site-packages/nanosv/__init__.py", line 1, in <module>
    from .utils import *
  File "/Users/tarekmagdyshehatamohamed/miniconda3/envs/bioinfo/lib/python3.6/site-packages/nanosv/utils/__init__.py", line 1, in <module>
    from . import coverage
  File "/Users/tarekmagdyshehatamohamed/miniconda3/envs/bioinfo/lib/python3.6/site-packages/nanosv/utils/coverage.py", line 8, in <module>
    import NanoSV
  File "/Users/tarekmagdyshehatamohamed/miniconda3/envs/bioinfo/lib/python3.6/site-packages/nanosv/utils/../NanoSV.py", line 29, in <module>
    cfg.read(args.config)
  File "/Users/tarekmagdyshehatamohamed/miniconda3/envs/bioinfo/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/Users/tarekmagdyshehatamohamed/miniconda3/envs/bioinfo/lib/python3.6/configparser.py", line 1015, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/Users/tarekmagdyshehatamohamed/miniconda3/envs/bioinfo/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 948: ordinal not in range(128)

```

**Comment by jaesvi** [comment] 2018-07-21 11:44
See #45

**Comment by herrroaa** [comment] 2018-07-21 13:03
Thanks for the reply
I added the two lines in my bashfiles, but did not work

**Comment by jaesvi** [comment] 2018-07-21 14:22
Did you source your .bashrc or restart your terminal?

**Comment by herrroaa** [comment] 2018-07-29 01:11
Any other suggestions?

**Comment by mroosmalen** [comment] 2018-08-01 06:51
Maybe you can try to make the following bash file (eg. nanosv.sh)

```
#!/usr/bin/bash

export LC_CTYPE=en_US.UTF-8
export LANG=en_US.UTF-8

NanoSV BC01_sorted.bam -o BC01.vcf
```

And try to execute this bash file like `./nanosv.sh`

**Comment by herrroaa** [comment] 2018-08-01 15:18
I tried it and unfortunately I got the same error message !

**Comment by mroosmalen** [comment] 2018-08-03 10:02
Can you check your environment variables to be sure:
```
echo $LANG
echo $LC_ALL
```
Both should give `en_US.UTF-8` as output.

You can also try this `export LC_ALL=en_US.UTF-8`.

And you also check the default encoding language in your python:
```
import sys
sys.getdefaultencoding()
```

**Comment by herrroaa** [comment] 2018-08-07 02:51
Hi, 
export LC_ALL=en_US.UTF-8 worked, but I have one more question  now.
I need to generate a bed file for hg38 with chrx notation.
I got simple_repeats_file is from http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/simpleRepeat.txt.gz 
and gaps_file is from http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/gap.txt.gz

I then unziped the files and renamed then gap.bed and  simpleRepeat.bed 

`genome = {
1: 248956422,
2: 242193529,
3: 198295559,
4: 190214555,
5: 181538259,
6: 170805979,
7: 159345973,
8: 145138636,
9: 138394717,
10: 133797422,
11: 135086622,
12: 133275309,
13: 114364328,
14: 107043718,
15: 101991189,
16: 90338345,
17: 83257441,
18: 80373285,
19: 58617616,
20: 64444167,
21: 46709983,
22: 50818468,
23: 156040895,
24: 57227415
}`

`simple_repeats_file = '/Users/tarekmagdyshehatamohamed/Downloads/gap.bed'
gaps_file = '/Users/tarekmagdyshehatamohamed/Downloads/simpleRepeat.bed'`

I then ran the .py file and I got this error message
$ cd /Users/tarekmagdyshehatamohamed/miniconda3/pkgs/nanosv-1.2.0-py36_1/lib/python3.6/site-packages/nanosv/bedfiles ;env "PYTHONIOENCODING=UTF-8" "PYTHONUNBUFFERED=1" /Users/tarekmagdyshehatamohamed/miniconda3/envs/pythontwopointseven/bin/python /Users/tarekmagdyshehatamohamed/.vscode/extensions/ms-python.python-2018.7.1/pythonFiles/PythonTools/visualstudio_py_launcher.py /Users/tarekmagdyshehatamohamed/miniconda3/pkgs/nanosv-1.2.0-py36_1/lib/python3.6/site-packages/nanosv/bedfiles 58853 34806ad9-833a-4524-8cd6-18ca4aa74f14 RedirectOutput,RedirectOutput /Users/tarekmagdyshehatamohamed/miniconda3/pkgs/nanosv-1.2.0-py36_1/lib/python3.6/site-packages/nanosv/bedfiles/create_human_hg38_bed.py
Traceback (most recent call last):
  File "/Users/tarekmagdyshehatamohamed/miniconda3/pkgs/nanosv-1.2.0-py36_1/lib/python3.6/site-packages/nanosv/bedfiles/create_human_hg38_bed.py", line 63, in <module>
    read_bed(simple_repeats_file)
  File "/Users/tarekmagdyshehatamohamed/miniconda3/pkgs/nanosv-1.2.0-py36_1/lib/python3.6/site-packages/nanosv/bedfiles/create_human_hg38_bed.py", line 46, in read_bed
    ch, start, end = line.split("\t")
ValueError: too many values to unpack

**Comment by mroosmalen** [comment] 2018-08-07 06:07
This is because the download file are not a proper bed file. First you need to convert the .txt file to a .bed file.
```
cut -f 2,3,4 gap.txt > gap.bed
cut -f 2,3,4 simpleRepeat.txt > simpleRepeat.bed
```
Maybe you should also remove the `chr` notation in front of the chromosome names, depends on the bam file, if this has also the `chr` notation or not.

**Comment by herrroaa** [comment] 2018-08-07 15:45
These are my bed files

$ cat gap.bed | head -n 10
```
chr1	0	10000
chr1	207666	257666
chr1	297968	347968
chr1	535988	585988
chr1	2702781	2746290
chr1	12954384	13004384
chr1	16799163	16849163
chr1	29552233	29553835
chr1	121976459	122026459
chr1	122224535	122224635
```

$ cat simpleRepeat.bed | head -n 5                        
```
chr1	10000	10468
chr1	10627	10800
chr1	10757	10997
chr1	11225	11447
chr1	11271	11448
```
When I run the .py file  I got this error
`$ cd /Users/tarekmagdyshehatamohamed/miniconda3/pkgs/nanosv-1.2.0-py36_1/lib/python3.6/site-packages/nanosv/bedfiles ;env "PYTHONIOENCODING=UTF-8" "PYTHONUNBUFFERED=1" /Users/tarekmagdyshehatamohamed/miniconda3/envs/pythontwopointseven/bin/python /Users/tarekmagdyshehatamohamed/.vscode/extensions/ms-python.python-2018.7.1/pythonFiles/PythonTools/visualstudio_py_launcher.py /Users/tarekmagdyshehatamohamed/miniconda3/pkgs/nanosv-1.2.0-py36_1/lib/python3.6/site-packages/nanosv/bedfiles 50921 34806ad9-833a-4524-8cd6-18ca4aa74f14 RedirectOutput,RedirectOutput /Users/tarekmagdyshehatamohamed/miniconda3/pkgs/nanosv-1.2.0-py36_1/lib/python3.6/site-packages/nanosv/bedfiles/create_human_hg38_bed.py
Traceback (most recent call last):
  File "/Users/tarekmagdyshehatamohamed/miniconda3/pkgs/nanosv-1.2.0-py36_1/lib/python3.6/site-packages/nanosv/bedfiles/create_human_hg38_bed.py", line 79, in <module>
    for mask_start in sorted(mask_regions[randchr]):
KeyError: 5`

**Comment by mroosmalen** [comment] 2018-08-08 05:40
It can't find chromsome `5` in the bedfile, because in the bed it has this `chr` notation.
Remove the `chr` notation in the bed file or add the `chr` notation to the chromsomes in the genome dictionary.

**Comment by herrroaa** [comment] 2018-08-08 17:09
I modified the genome dictionary as follows,
`genome = {
'chr1': 248956422,
'chr2': 242193529,
'chr3': 198295559,
'chr4': 190214555,
'chr5': 181538259,
'chr6': 170805979,
'chr7': 159345973,
'chr8': 145138636,
'chr9': 138394717,
'chr10': 133797422,
'chr11': 135086622,
'chr12': 133275309,
'chr13': 114364328,
'chr14': 107043718,
'chr15': 101991189,
'chr16': 90338345,
'chr17': 83257441,
'chr18': 80373285,
'chr19': 58617616,
'chr20': 64444167,
'chr21': 46709983,
'chr22': 50818468,
'chr23': 156040895,
'chr24': 57227415
}`

I ran the .py file multiple times, it gave me the same error with different unfound chr
`for mask_start in sorted(mask_regions[randchr]):
KeyError: 'chr18'`

'for mask_start in sorted(mask_regions[randchr]):
KeyError: 'chr11'

I checked the bed files for these chrs

`$ cat gap.bed | grep 'chr18' | head -n 5
chr18	0	10000
chr18	15410899	15460899
chr18	15780377	15780477
chr18	15788380	15791047
chr18	15797755	15797855


$ cat gap.bed | grep 'chr11' | head -n 5
chr11	0	10000
chr11	10000	60000
chr11	50821348	50871348
chr11	50871348	51078348
chr11	51090317	51090417
`
`$ cat gap.bed | grep 'chr18' | head -n 5
chr18	0	10000
chr18	15410899	15460899
chr18	15780377	15780477
chr18	15788380	15791047
chr18	15797755	15797855

$ cat gap.bed | grep 'chr11' | head -n 5
chr11	0	10000
chr11	10000	60000
chr11	50821348	50871348
chr11	50871348	51078348
chr11	51090317	51090417

`

**Comment by mroosmalen** [comment] 2018-08-09 05:51
There was a minor bug in the script. This should be fixed by now, in the newest version of NanoSV (v.1.2.1)

**Comment by herrroaa** [comment] 2018-08-09 15:33
I modified the genome dictionary as follows,
```
genome = {
    'chr1': 248956422,
    'chr2': 242193529,
    'chr3': 198295559,
    'chr4': 190214555,
    'chr5': 181538259,
    'chr6': 170805979,
    'chr7': 159345973,
    'chr8': 145138636,
    'chr9': 138394717,
    'chr10': 133797422,
    'chr11': 135086622,
    'chr12': 133275309,
    'chr13': 114364328,
    'chr14': 107043718,
    'chr15': 101991189,
    'chr16': 90338345,
    'chr17': 83257441,
    'chr18': 80373285,
    'chr19': 58617616,
    'chr20': 64444167,
    'chr21': 46709983,
    'chr22': 50818468,
    'chrX': 156040895,
    'chrY': 57227415
}
```
Then I ran the new .py script several times in python 3.6.3 after modifying `genome.itertitems()` to `genome.items()`

I git this error
```
Traceback (most recent call last):
  File "/Users/tarekmagdyshehatamohamed/miniconda3/pkgs/nanosv-1.2.0-py36_1/lib/python3.6/site-packages/nanosv/bedfiles/test02.py", line 75, in <module>
    randchr = randchr.replace('chr','')
AttributeError: 'int' object has no attribute 'replace'
```
I also tried it by removing the `chr` notation from my two bed files with the original genome dictionary, and I got the same error as above.

```
genome = {
1: 248956422,
2: 242193529,
3: 198295559,
4: 190214555,
5: 181538259,
6: 170805979,
7: 159345973,
8: 145138636,
9: 138394717,
10: 133797422,
11: 135086622,
12: 133275309,
13: 114364328,
14: 107043718,
15: 101991189,
16: 90338345,
17: 83257441,
18: 80373285,
19: 58617616,
20: 64444167,
21: 46709983,
22: 50818468,
23: 156040895,
}
```

```
cat simpleRepreat.bed | sed s/chr// > simpleRepeate_nochr.bed
cat gap.bed | sed s/chr// > gap_nochr.bed
```

```
$ cat gap_nochr.bed | head -n 5 
1	0	10000
1	207666	257666
1	297968	347968
1	535988	585988
1	2702781	2746290
```

```
$ cat simpleRepeat_nochr.bed | head -n 5
1	10000	10468
1	10627	10800
1	10757	10997
1	11225	11447
1	11271	11448
```

**Comment by mroosmalen** [comment] 2018-08-10 06:03
Sorry but there were still some bugs in the script. Can you try it again with the newest version (1.2.2)

**Comment by herrroaa** [comment] 2018-08-14 18:02
Any thoughts ?

**Comment by mroosmalen** [comment] 2018-08-15 05:59
And if you try this on a subset of your bed file:
```
$SAMTOOLS depth $BAM -b $BEDFILE | awk '{print $3}'
```
Do you get any result?

**Comment by herrroaa** [comment] 2018-08-15 17:39
yes I got some results
```
$ samtools depth BC01_sorted.bam -b hg38_withchr02_xyy.bed | awk '{print $3}' | head -n 5
1
1
1
1
1

```

**Comment by mroosmalen** [comment] 2018-08-16 05:44
Did you use the same samtools path (I see `samtools` and `/Users/tarekmagdyshehatamohamed/miniconda3/pkgs/samtools-1.8-3/bin/samtools`? NanoSV execute the previous command to calculate the distribution and if it returns an empty list than you will get this error. But is seems that it will returns a list, so it should work.

I think the problem is samtools and the libdeflate.so library.

**Closed** 2019-10-03 15:12 UTC
